timezone: Asia/Shanghai

tasks:
  daily_maintenance_report:
    enabled: true
    schedule:
      hour: 2
      minute: 0
    parameters:
      channel_id: "3702137"
      max_age_seconds: 30
      usage_top_limit: 5

  send_fans_and_guards_message:
    enabled: true
    schedule:
      hour: 23
      minute: 55
    parameters:
      channel_id: "8338248"
      category: wan
